### ISSUE TITLE
Error while providing custom podAnnotations for eks/appmesh-controller

### ISSUE THREAD

**Issue by janario** [aws/eks-charts#117]
We would like to provide some custom annotations but it fails while installing

```
Error: YAML parse error on appmesh-controller/templates/deployment.yaml: error converting YAML to JSON: yaml: line 24: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 24: did not find expected key

```

I've tried to run the template to see more details and it seems to have a indentation problem

```
# values-for-appmesh-controller.yaml
podAnnotations:
  custom: test

helm template -f ./values-for-appmesh-controller.yaml  eks/appmesh-controller --debug

...
      annotations:
        prometheus.io/scrape: "true"
          custom: "test"
...
correct would be:
      annotations:
        prometheus.io/scrape: "true"
        custom: "test"
```
