### ISSUE TITLE
[aws-for-fluent-bit] firehose.extraOutputs doesn't use in template

### ISSUE THREAD

**Issue by guitarrapc** [aws/eks-charts#1187]
**Describe the bug**
Even if user set `firehose.extraOutputs` helm template not referencing this key, but it refer `kinesis.extraOutputs`.

This led by following typo, `.Values.kinesis.extraOutputs` should be `.Values.firehose.extraOutputs`.

```yaml
        {{- if .Values.kinesis.extraOutputs }}
{{ .Values.kinesis.extraOutputs | indent 8 }}
        {{- end }}
```

https://github.com/aws/eks-charts/blob/ef3f3145682b25cfb264a567d579ea59adcc561f/stable/aws-for-fluent-bit/templates/configmap.yaml#L186-L188

**Steps to reproduce**

even if set extraOutputs, output is not referencing to `[OUTPUT]`.

```yaml
firehose:
  enabled: true
  match: "foo.*"
  region: "us-east-1"
  deliveryStream: "some-delivery-name"
  dataKeys:
  roleArn:
  endpoint:
  timeKey:
  extraOutputs: |
    replace_dots  _
```

```yaml
[OUTPUT]
   Name            firehose
    Match           foo.*
    region          us-east-1
   delivery_stream some-delivery-name
```

**Expected outcome**
```
[OUTPUT]
   Name            firehose
    Match           foo.*
    region          us-east-1
   delivery_stream some-delivery-name
    replace_dots  _
```

**Environment**

* Chart name: aws-for-fluent-bit
* Chart version: 0.1.34
* Kubernetes version: n/a
* Using EKS (yes/no), if so version? n/a

**Additional Context**:
