### ISSUE TITLE
Calico Helm chart doesn't support nodeAffinity or nodeSelector configuration

### ISSUE THREAD

**Issue by szpuni** [aws/eks-charts#177]
Currently calico helm chart do not allow for nodeSelector or nodeAffinity manipulation. Tolerations are only available in one of deployments are are hardcoded same way as 2 previous attributes.

Above makes impossible to choose nodes in cluster on which calico is installed.

Deployment.yaml file needs to be updated to allow using custom values in nodeSelector, nodeAffinity, tollerations:

```
    spec:
      priorityClassName: system-cluster-critical
      nodeSelector:
        beta.kubernetes.io/os: linux
      tolerations:
        # Mark the pod as a critical add-on for rescheduling.
        - key: CriticalAddonsOnly
          operator: Exists
```
