### ISSUE TITLE
Cannot upgrade to aws-node-termination-handler 1.6.1 from 1.5.0

### ISSUE THREAD

**Issue by AlexMichaelJonesNC** [aws/eks-charts#215]
Attempting to upgrade an existing installation of aws-node-termination-handler to 1.6.1 results in the following error: 

```
Error: UPGRADE FAILED: cannot patch "aws-node-termination-handler" with kind DaemonSet: DaemonSet.apps "aws-node-termination-handler" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"aws-node-termination-handler", "app.kubernetes.io/name":"aws-node-termination-handler", "kubernetes.io/os":"linux"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

This seems to be caused by https://github.com/aws/eks-charts/commit/5240106c457b17ca08134821ab101cdcc341e8fc updating stable/aws-node-termination-handler/templates/daemonset.linux.yaml with spec.selector with a new field: `         {{ include "aws-node-termination-handler.nodeSelectorTermsOs" . }}: linux`

A work around is to uninstall and reinstall the chart, but a clean upgrade would be preferred.

**Comment by bwagner5** [comment]
Thanks for letting us know! We'll look into this update problem soon.

**Comment by bwagner5** [comment]
Before, we were using the beta node selector os key. I'm pretty sure that is the issue, but I can try to verify tomorrow. We may be able to change the condition to only use the non-beta key when the cluster is 1.19 or later since beta seems to still be supported on <= 1.18

**Comment by AlexMichaelJonesNC** [comment]
Unless I'm looking at the wrong field, our install actually isn't showing an OS key at all.  It's possible that somehow we managed to get the selector in a weird state in a previous deployment, but I'm not sure how we'd accomplish that and only notice as 1.6.1 or 1.6.2 was related. 

```
spec
  selector:
    matchLabels:
      app.kubernetes.io/instance: aws-node-termination-handler
      app.kubernetes.io/name: aws-node-termination-handler
```

**Comment by bwagner5** [comment]
It's the nodeSelectorTerms for node affinity: 

```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "kubernetes.io/os"
                  operator: In
                  values:
                    - linux
                - key: "kubernetes.io/arch"
                  operator: In
                  values:
                    - amd64
                    - arm64
                    - arm
                - key: "eks.amazonaws.com/compute-type"
                  operator: NotIn
                  values:
                    - fargate
```
