### ISSUE TITLE
[aws-load-balancer-controller] boolean false controller arg values aren't templated

### ISSUE THREAD

**Issue by nicholasmhughes** [aws/eks-charts#357]
Since [the controller defaults certain args to "true"](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/guide/controller/configurations.md#controller-command-line-flags), I tried to to turn them off by passing `--set enableShield=false` (and similar for waf and wafv2) to the helm chart.

However, the `helm template` output did not include the args set to `false` as expected:

```
      containers:
      - name: aws-load-balancer-controller
        args:
        - --cluster-name=mycluster
        - --ingress-class=alb
```

This can be traced to the test in the template only handled "truthy" values in order to expose the template section in the deployment:

```
         {{- if .Values.enableShield }}
         - --enable-shield={{ .Values.enableShield }}
         {{- end }}
```

I would expect instead to be able to turn off boolean options in the helm chart and have the deployment template rendered as below:

```
      containers:
      - name: aws-load-balancer-controller
        args:
        - --cluster-name=mycluster
        - --ingress-class=alb
        - --enable-shield=false
        - --enable-waf=false
        - --enable-wafv2=false
```

PR incoming.
