### ISSUE TITLE
[aws-calico] annotations for typha pods do not render correctly

### ISSUE THREAD

**Issue by spingel** [aws/eks-charts#360]
Steps:
1. Define annotations in stable/aws-calico/values.yml for typha and typha_autoscaler

The annotation key is duplicated and annotations are not placed at the right level in the hierarchy.

Actual output:

```yaml
# Source: aws-calico/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "calico-typha"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "calico-typha"
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
        annotations:
          foo: bar
...
# Source: aws-calico/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "calico-typha-horizontal-autoscaler"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "calico-typha-autoscaler"
        annotations:
          foo: bar
```

Expected output:

```yaml
# Source: aws-calico/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "calico-typha"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "calico-typha"
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
        foo: bar
...
---
# Source: aws-calico/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "calico-typha-horizontal-autoscaler"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "calico-typha-autoscaler"
      annotations:
        foo: bar
```
