### ISSUE TITLE
[aws-vpc-cni] Add variable for additional resources

### ISSUE THREAD

**Issue by sidewinder12s** [aws/eks-charts#453]
**Is your feature request related to a problem?**
Currently you need to manage the ENIConfig's if using custom networking separately from the vpc-cni plugin chart.

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
aws-vpc-cni is the one I'm interested in but I suppose it could be applicable to all.

**Describe the solution you'd like**
A few of the bitnami charts have this feature, where you can easily pass in kube YAML into the chart for additional resources that'll be managed by the chart. 

https://github.com/bitnami/charts/blob/master/bitnami/kubernetes-event-exporter/values.yaml#L207

Specifically I'd like to be able to manage the ENIConfigs alongside the vpc-cni plugin chart.

**Describe alternatives you've considered**
We currently manage ENIConfigs separately, but it'd be nice to be able to deploy them along side the CNI Plugin since they are dependent.

**Comment by jwenz723** [comment]
Another option would be to add something like this into the aws-vpc-cni chart:

```yaml
{{- range $key, $value := (required ".Values.subnets must be specified" .Values.subnets) }}
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
  name: {{ required ".Values.region must be specified" $.Values.region }}{{ $key }}
spec:
  {{- if $value.securityGroups }}
  securityGroups:
    {{- toYaml $value.securityGroups | nindent 4 }}
  {{- end }}
  subnet: {{ $value.id }}
---
{{- end }}
```

This would then allow you to specify your subnets for which ENIConfigs should be created in your values.yaml file like this:

```yaml
region: "us-west-2"
subnets:
  # Key identifies the AZ
  # Value contains the subnet ID and security group IDs within that AZ
  a:
    id: subnet-123
    securityGroups:
    - sg-123
  b:
    id: subnet-456
    securityGroups:
    - sg-456
  c:
    id: subnet-789
    securityGroups:
    - sg-789
```
