### ISSUE TITLE
Feature Request: App Mesh Gateway add Support for passing Multiple Port List Items

### ISSUE THREAD

**Issue by colinbjohnson** [aws/eks-charts#455]
**Is your feature request related to a problem?**

I believe the appmesh-gateway service should support multiple "port" configurations in the `eks-charts/stable/appmesh-gateway/templates/service.yaml` file so that I can accept traffic on both ports 80 and 443.

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**

appmesh-gateway

**Describe the solution you'd like**

I would like the appmesh-gateway to support multiple "port" list items. The current configuration is:

```
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    name: http
    protocol: TCP
```

But I believe a list of "ports" should be able to be passed in.

**Describe alternatives you've considered**

Options I've considered:

- submitting a PR with a fix
- modifying the load balancer _after_ creating the App Mesh helm chart.
