### ISSUE TITLE
Does the current Crds supports appmesh.k8s.aws/v1beta2 

### ISSUE THREAD

**Issue by shubham-khatri-121** [aws/eks-charts#464]
**Describe the bug**
I want to setup multi cluster mesh in EKS, first I was following this [blog  ](https://aws.amazon.com/blogs/containers/cross-amazon-eks-cluster-app-mesh-using-aws-cloud-map/). This blog seems to be outdated as it includes a step to install appmesh-inject, which is deprecated. I have created a helm chart to create below given resources. 

- VirtualNode
- VirtualRouter
- VirtualService

**Steps to reproduce**

kubectl apply -k "https://github.com/aws/eks-charts/stable/appmesh-controller/crds?ref=master"
kubectl create ns appmesh-system
helm install  appmesh-controller  -f values.yaml eks/appmesh-controller  --namespace appmesh-system

**values.yaml**
```
region: ap-southeast-1
serviceAccount:
  create: false
  name: appmesh-controller
  
tracing:
  enabled: true
  provider: x-ray  
  
sidecar:
  image:
    repository: public.ecr.aws/appmesh/aws-appmesh-envoy
    tag : v1.16.1.1-prod
```

**virtual-node.yaml**
```
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}  
spec:
  podSelector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  listeners:
    - portMapping:
        port: {{ .Values.service.port }}
        protocol: http
  serviceDiscovery:
    awsCloudMap:
      namespaceName: {{.Values.cloudmap.namespace}}
      serviceName: {{ include "app.fullname" . }}
```
**virtual-router.yaml**
```
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: {{ include "app.fullname" . }}-router
spec:
  listeners:
    - portMapping:
        port: {{ .Values.service.port }}
        protocol: http
  routes:
    - name: {{ include "app.fullname" . }}-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name:  {{ include "app.fullname" . }}
              weight: 1
```
***virtual-service.yaml**
```
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: {{ include "app.fullname" . }}
spec:
  awsName: {{ include "app.fullname" . }}.{{.Release.Namespace}}.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: {{ include "app.fullname" . }}-router
```

**Error**
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "VirtualNode" in version "appmesh.k8s.aws/v1beta2", unable to recognize "": no matches for kind "VirtualRouter" in version "appmesh.k8s.aws/v1beta2", unable to recognize "": no matches for kind "VirtualService" in version "appmesh.k8s.aws/v1beta2"]

* Chart name: appmesh-controller-1.3.0  
* Chart version: 1.3.0  
* Kubernetes version: 1.18
* Using EKS (yes/no), if so version? Yes -> eks.3
