### ISSUE TITLE
[AWS Load Balancer Controller ] helm chart ignores  --set enableWaf=false --set enableWafv2=false --set enableShield=false parameters

### ISSUE THREAD

**Issue by alexmnyc** [aws/eks-charts#511]
**Describe the bug**
helm chart ignores  `--set enableWaf=false --set enableWafv2=false --set enableShield=false` parameters

**Steps to reproduce**

	helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=$$TF_VAR_cluster_name --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller --set image.tag="v2.1.3" --set image.repository="docker.io/amazon/aws-alb-ingress-controller" --set region=$AWS_DEFAULT_REGION --set vpcId="vpc-XXX" --set enableWaf=false --set enableWafv2=false --set enableShield=false

**Expected outcome**
settings those parameters to false should disalbe `enable-waf` `enable-wafv2` and `enable-shield` parameters according to https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/v2.1.3/docs/deploy/configurations.md
however, alb controller continues to print out Error regarding WAF in the logs and ingress provisioning errors out half-way (ALB is created but the ingress CNAME of the ALB is never shown via kubernetes API)

Log error is

```
is not authorized to perform: wafv2:GetWebACLForResource on resource: arn:aws:wafv2:us...
```
**Environment**

* Chart name: eks/aws-load-balancer-controller
* Chart version: 2.1.3
* Kubernetes version: EKS 1.19
* Using EKS (yes/no), if so version? yes 1.19

**Additional Context**:

**Comment by kishorj** [comment]
@alexmnyc 
what does the controller deployment spec look like? If the following controller flags are set to false, helm chart got installed as expected -
```
      ...
      containers:
      - name: aws-load-balancer-controller
        args:
        - --cluster-name=xxxx
        - --ingress-class=alb
        - --enable-shield=false
        - --enable-waf=false
        - --enable-wafv2=false
        command:
        - /controller
        ...
```
