### ISSUE TITLE
[aws-load-balancer-controller] podAntiAffinity is rendered two times if custom affinity is specified.

### ISSUE THREAD

**Issue by r0bobo** [aws/eks-charts#524]
**Describe the bug**
If a custom podAntiAffinity is specified in the helm chart values the antiAffinity field is added two times to the controller pod spec producing invalid manifests. Relevant code [here](https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/templates/deployment.yaml#L138-L152).

**Steps to reproduce**
Render aws-load-balancer-chart with following in values file:
```
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              example.com/affinity-label: aws-load-balancer-controller
          topologyKey: topology.kubernetes.io/zone
        weight: 100
```

**Expected outcome**
I expected the antiAffinities to be merged and produce a valid manifest.

**Environment**

* Chart name: aws-load-balancer-controller
* Chart version: 1.2.0
* Kubernetes version: v1.19.8
* Using EKS (yes/no), if so version? v1.19.8-eks-96780e
