### ISSUE TITLE
[aws-load-balancer-controller] Internal error occurred: failed calling webhook "vingress.elbv2.k8s.aws": the server could not find the requested resource

### ISSUE THREAD

**Issue by kaykhancheckpoint** [aws/eks-charts#534]
**Describe the bug**

After upgrading from 2.13 -> 2.2.0. I now get the following error when i try to update an ingeress file.

`
kubetl apply -f monitoring.ingress.yml
`
> Internal error occurred: failed calling webhook "vingress.elbv2.k8s.aws": the server could not find the requested resource

**Steps to reproduce**

Upgrade from 2.13 to 2.20 on eks 1.19

**Expected outcome**
Expect the ingress to successfully paply

**Environment**

* Chart name: aws-load-balancer-controller
* Chart version: 2.2.0
* Kubernetes version: 1.19
* Using EKS (yes/no), if so version? yes

**Additional Context**:

Im trying to apply the new ssl redirect to an existing ingress
```    
alb.ingress.kubernetes.io/ssl-redirect: '443'
```

This looks to be related (https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2039), althoujgh im not sure how to recreate the service account as that seems to be created automatically by the chart.

**values.yml**

```
image:
  repository: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller
  tag: v2.2.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "kube-system"
fullnameOverride: ""

# The name of the Kubernetes cluster. A non-empty value is required
clusterName: "<redacted>

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<redacted>:role/AWSLoadBalancerControllerIAMRole
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "aws-load-balancer-controller"
  # Automount API credentials for a Service Account.
  automountServiceAccountToken: true

rbac:
  # Specifies whether rbac resources should be created
  create: true
```
