### ISSUE TITLE
Calico v3.19.1 Upgrade Fails

### ISSUE THREAD

**Issue by cmukai-cisco** [aws/eks-charts#537]
**Describe the bug**
Upgrading to Calico v3.19.1 using stable/aws-calico chart does not launch the CNI.

**Steps to reproduce**
We are currently running v3.15.1, so I cleaned it up as follows:
1. helm -n kube-system uninstall aws-calico

Then install Calico v3.19.1 as follows:
1. git clone https://github.com/aws/eks-charts.git
2. cd eks-charts/stable
3. create custom values.yaml with the following content:
```
calico:
  tag: v3.19.1
```
4. kubectl apply -k aws-calico/crds
5. helm -n kube-system install -f values.yaml aws-calico ./aws-calico
6. kubectl -n kube-system describe pod \<calico-typha-horizontal-autoscaler-pod-name\>
7. note the following warning in the events:
```
Warning  FailedCreatePodSandBox  34s               kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "72944aaaa37cd176e948865cd20b5c11a3900bdd9e1d644680ad82ba520b2c42" network for pod "calico-typha-horizontal-autoscaler-5bfc7d6966-h7c8z": networkPlugin cni failed to set up pod "calico-typha-horizontal-autoscaler-5bfc7d6966-h7c8z_kube-system" network: error getting ClusterInformation: connection is unauthorized: Unauthorized, failed to clean up sandbox container "72944aaaa37cd176e948865cd20b5c11a3900bdd9e1d644680ad82ba520b2c42" network for pod "calico-typha-horizontal-autoscaler-5bfc7d6966-h7c8z": networkPlugin cni failed to teardown pod "calico-typha-horizontal-autoscaler-5bfc7d6966-h7c8z_kube-system" network: error getting ClusterInformation: connection is unauthorized: Unauthorized]
```

The service account for this pod is `calico-typha-cpha`. This is bound to the role of the same name. The helm chart defining this role is:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "aws-calico.fullname" . }}-typha-cpha"
  labels:
{{ include "aws-calico.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "update"]
```

It does not allow access to ClusterInformation resources.

Also calico-node pods are constantly restarting.

**Expected outcome**
All Calico pods using v3.19.1 should come up cleanly.

**Environment**
AWS

* Chart name: stable/aws-calico
* Chart version: 0.3.5
* Kubernetes version: 1.18
* Using EKS (yes/no), if so version? yes, eks.3

**Additional Context**:
