### ISSUE TITLE
the additional pod annotations for the typha deployment creates a nested annotations dictionary

### ISSUE THREAD

**Issue by wyndigo** [aws/eks-charts#554]
**Describe the bug**
when you set an annotation for the typha pods, it creates a nested annotations dictionary under annotations instead of setting the annotation at the top level.

**Steps to reproduce**
```
helm template eks/aws-calico --set calico.typha.podAnnotations.foo=bar | grep -C 5 bar

      labels:
        app.kubernetes.io/name: "calico-typha"
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
        annotations:
          foo: bar
    spec:
      priorityClassName: system-cluster-critical
      nodeSelector:
        beta.kubernetes.io/os: linux
      tolerations:
 ```
**Expected outcome**
```
helm template eks/aws-calico --set calico.typha.podAnnotations.foo=bar | grep -C 5 bar

      labels:
        app.kubernetes.io/name: "calico-typha"
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
        foo: bar
    spec:
      priorityClassName: system-cluster-critical
      nodeSelector:
        beta.kubernetes.io/os: linux
      tolerations:
 ```

**Environment**
EKS
* Chart name: aws-calica
* Chart version: 0.3.6
* Kubernetes version: 1.18+
* Using EKS: yes 

**Additional Context**:
