### ISSUE TITLE
When using extra input and/or filter and/or output, the configmap created is not correct and fluentbit failed to start

### ISSUE THREAD

**Issue by ltupin** [aws/eks-charts#657]
When you want to use extra filter/input/output options it is confusing in comments to leave the title itself. 

## Example 1:

The example you will find in `values.yaml` is:
```
# extraFilters: |
#   [FILTER]
#       Name   grep
#       Match  *
#       Exclude log lvl=debug*
```

If you keep it "as-is" just with uncomenting the `values.yaml` and add a filter option, for example :  

```
filter:
  match: "kube.*"
  kubeURL: "https://kubernetes.default.svc.cluster.local:443"
  mergeLog: "On"
  mergeLogKey: "data"
  keepLog: "On"
  k8sLoggingParser: "On"
  k8sLoggingExclude: "On"

extraFilters: |
  [FILTER]
      Use_Kubelet      On
```

You will get a `configmap` like this one, which is not working with fluentbit (it starts but won't take your extra options) :

```
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        Merge_Log_Key       data
        Keep_Log            On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
    [FILTER]
        Use_Kubelet            On
```

and the error in fluentbit logs:
```
Invalid configuration value at FILTER.Name
```

## Example 2:

Let's now try to use extra filter **without** the title, such as this example:

```
filter:
  match: "kube.*"
  kubeURL: "https://kubernetes.default.svc.cluster.local:443"
  mergeLog: "On"
  mergeLogKey: "data"
  keepLog: "On"
  k8sLoggingParser: "On"
  k8sLoggingExclude: "On"

extraFilter: |
      Use_Kubelet            On
```

you will get a `configmap` like this one, which is not working with fluentbit (it starts but won't take your extra options) :
```
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        Merge_Log_Key       data
        Keep_Log            On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
    Use_Kubelet            On
```

and the error in fluentbit logs:
```
[  Error] Error in line 24: Invalid indentation level
Error: Configuration file contains errors. Aborting
```

That's why I want to propose a PR to indent from 4 to 8, any extra option and to remove the block configuration title FILTER/INPUT and OUTPUT in comments in values file. 

The only block within I didn't try it is the PARSER so that's why I don't submit any change for this one (but maybe it is needed too).
