### ISSUE TITLE
Indentation error on Node Termination Handler deployment

### ISSUE THREAD

**Issue by prikesh-patel** [aws/eks-charts#682]
**Describe the bug**
When upgrading to AWS Node Termination Handler chart v0.16.1, I get the following error

```shell
Error: YAML parse error on aws-node-termination-handler/templates/deployment.yaml: error converting YAML to JSON: yaml: line 110: did not find expected '-' indicator
helm.go:88: [debug] error converting YAML to JSON: yaml: line 110: did not find expected '-' indicator
YAML parse error on aws-node-termination-handler/templates/deployment.yaml
```

This is where the deployment object seems to be failing

```yaml
# Source: aws-node-termination-handler/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-node-termination-handler
  labels: ...
spec:
  replicas: 2
  selector: ...
  template:
    metadata: ...
    spec:
      serviceAccountName: aws-node-termination-handler
      securityContext: ...
      priorityClassName: system-cluster-critical
      containers:
        - name: aws-node-termination-handler
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          image: public.ecr.aws/aws-ec2/aws-node-termination-handler:v1.14.1
          imagePullPolicy: IfNotPresent
          env: ...
          ports:
           - name: liveness-probe
             protocol: TCP
             containerPort: 8080
            - name: http-metrics
              protocol: TCP
              containerPort: 9092
          livenessProbe: ...
          resources: ...
      nodeSelector: ...
      affinity: ...
      tolerations: ...
```

From the templates, it looks like these [3 lines](https://github.com/aws/eks-charts/blob/master/stable/aws-node-termination-handler/templates/deployment.yaml#L164-L166) should be indented to the right by 1 space.

**Steps to reproduce**
Upgrade to AWS Node Termination Handler chart v0.16.1, from chart v0.16.0.

**Expected outcome**
Chart to successfully upgrade.

**Environment**

* Chart name: AWS Node Termination Handler
* Chart version: 0.16.1
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? Yes, v1.21.

**Additional Context**:
N/A
