### ISSUE TITLE
[aws-vpc-cni] cannot be configured for QoS class: guaranteed because of missing resource section for init container

### ISSUE THREAD

**Issue by universam1** [aws/eks-charts#738]
**Describe the bug**

In order to [workaround a known problem](https://github.com/aws/amazon-vpc-cni-k8s/issues/1425#issuecomment-1083271708), the pods need to be configured for `QoS class: guaranteed`.
However, due to missing resource section for the init container, it is not possible to configure the pod accordingly.

https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed

**Steps to reproduce**

configure custom values to be:
```yaml
resources:
  requests:
    cpu: 50m
    memory: 80Mi
  limits:
    cpu: 50m
    memory: 80Mi
```

The deployed the pod has class `QoS Class:  Burstable` and should be `guaranteed`

ref: https://github.com/aws/amazon-vpc-cni-k8s/issues/1425#issuecomment-1083271708
