### ISSUE TITLE
[aws-load-balancer-controller] Unexpected ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by cferrera** [aws/eks-charts#774]
**Describe the bug**
[annotations source](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/annotations/)
I have a NLB configured with the following annotations for a traefik ingress:
```
metadata:
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: traefik
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4
    service.beta.kubernetes.io/aws-load-balancer-name: dev-traefik
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
```
Some of the annotations were deprecated so I decided to updated them, using the following config:
```
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
    service.beta.kubernetes.io/aws-load-balancer-name: dev-traefik
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/load-balancer-source-ranges: 0.0.0.0/0
```
Everything deployed fine but right now all the requests are resolving into a `ERR_SSL_PROTOCOL_ERROR`.
I've tried *A LOT* of combinations and the only annotation that changes anything is:
```
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
```

I thought it could be some issues with traefik but it doesn't show any logs at all when using the new config so I assume that there are some issues in the targetGroup that doesn't even send the traffic to the cluster.

Since the annotations are deprecated I don't for how long they will be supported and if I can keep my cluster up-to-date will be great.

Do you have any idea what to do or if I'm doing anything wrong? 

** As a side note, the annotation for the name doesn't take effect when `type: nlb` is set.

**Steps to reproduce**
Create two services with these annotations:
1. This one works.
```
metadata:
  annotations:
    ...
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
```

2. This one doesn't work.
```
metadata:
  annotations:
    ...
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
```

**Expected outcome**
Request reaches the cluster and displays the content.

**Environment**

* Chart name: https://aws.github.io/eks-charts/aws-load-balancer-controller
* Chart version: 1.4.2
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? yes, eks.7

**Additional Context**:
N/A
