### ISSUE TITLE
Errors after updating aws-load-balancer-controller chart to version 1.0.8

### ISSUE THREAD

**Issue by iamyogeshg** [aws/eks-charts#883]
**Describe the bug**
We are upgrading from EKS 1.21 to 1.22 and as part of that trying to update from alb ingress 1.1.9 to load balancer 2.0.1 as mentioned here: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/deploy/upgrade/migrate_v1_v2/
There's a pre requisite to update to load balancer v2.4.1 for EKS 1.22

We are seeing lot of reconciler errors however not sure where is this tag which is not satisfying the regex condition. Its definitely not in the ingress manifest. 
```
{"level":"error","ts":1673655509.5978131,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"uat-main-test-ing","namespace":"uat-main-test","error":"ValidationError: 2 validation errors detected: Value '\"2020-09-24-13-38-38\"' at 'tags.1.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: ^([\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*)$; Value '\"eks\"' at 'tags.4.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: ^([\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*)$\n\tstatus code: 400, request id: 001420c3-b227-489b-9b19-9f712885fb24"}
{"level":"error","ts":1673655488.8118699,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"dev-main","namespace":"dev-main","error":"ValidationError: 2 validation errors detected: Value '\"2020-04-08-00-31-45\"' at 'tags.1.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: ^([\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*)$; Value '\"eks\"' at 'tags.4.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: ^([\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*)$\n\tstatus code: 400, request id: f2a430d3-45cc-498a-97f5-85d789be361d"}
```

Ingress snippet:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:blah-blah
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=blah-blah
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/security-groups: sg-0XXXXXXX
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
    alb.ingress.kubernetes.io/tags: name=dev-main, env=dev, instance=main, platform=eks, projectref=app-deployments/k8s-ingresses
    alb.ingress.kubernetes.io/target-type: ip
```

**Steps to reproduce**

- Have a EKS cluster 1.21 with ingresses setup with alb ingress 1.1.9
- Cleanup alb ingress and install load balancer 2.0.1 with helm
```
helm upgrade --install {{ item }} eks/{{ item }} --namespace kube-system --version {{ aws_load_balancer_ver }} --set clusterName={{ aws_eks_cluster }} --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="{{ load_balancer_role }}"  --set region=ap-southeast-2 --set image.repository=602401143452.dkr.ecr.{{region-code}}.amazonaws.com/amazon/aws-load-balancer-controller
```

**Expected outcome**
No such errors. Due to these errors we are not comfortable to upgrade EKS to 1.22 just yet.

**Environment**

* Chart name: aws-load-balancer-controller
* Chart version: 1.0.8
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? yes, 1.21

**Comment by iamyogeshg** [comment]
I think i found the issue, the tags were in one of the backend services for ingress. 

It does not like the double quotes in tags as can be seen below:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/tags: name=main-lb, env=dev,
      instance=main, platform="eks", date_created="2020-09-24-13-38-38"
```

After removing tags, the reconciler error from load balancer logs is gone.
