### ISSUE TITLE
Add some configuration Examples

### ISSUE THREAD

**Issue by maxmonterumisi** [aws/eks-charts#925]
Hi,
 I'm sorry but I cannot find good configuration examples to use this eks-charts.
For examples I would to like send my Fluentbit logs to S3 trough Firehose for log storaging, and to Cloudwatch for a quick log analisys.

I create a aws_for_fluentbit-values.yaml like that:
```
serviceAccount:
  create: true
  name: "aws-for-fluent-bit-sa"

# These plugins are not used in this example. They are enabled by default if not explicitly disabled
elasticsearch:
  enabled: false

firehose:
  enabled: true
  match: "*"
  region: ${aws_region}
  deliveryStream: ${cluster}-stream

kinesis:
  enabled: false

cloudWatch:
  enabled: true
  region: ${aws_region}
  logGroupName: /aws/eks/${cluster}/logs
  logRetentionDays: 90
```

Question:
 - I don't find the S3 bucket parameter under firehose , for example `aws firehose create-delivery-stream --delivery-stream-name eks-stream --delivery-stream-type DirectPut --s3-destination-configuration RoleARN=${FIREHOSE_ROLE_ARN},BucketARN=${S3_BUCKET_ARN},Prefix=eks/`

Please add to docuumtation some practical working examples.
