### ISSUE TITLE
aws-for-fluent-bit: provide realistic runAsNonRoot pod security policy values

### ISSUE THREAD

**Issue by joebowbeer** [aws/eks-charts#928]
Provide realistic values for running fluent-bit as a non-root user

              I am not sure what securityContext Fluent Bit needs to run correctly.  Once this is change is in a think a separate PR could be used to determine what a default standard policy should look like.

_Originally posted by @razorsk8jz in https://github.com/aws/eks-charts/pull/923#discussion_r1142587589_

**Comment by razorsk8jz** [comment]
Posted in the RFE but i aws able to get aws-for-fluent-bit running as

```
podSecurityContext:
  runAsUser: 0
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  privileged: false
  capabilities:
    drop:
    - ALL
```
