### ISSUE TITLE
Hardcoded namespace in spire charts

### ISSUE THREAD

**Issue by mconigliaro** [aws/eks-charts#956]
**Describe the bug**

In `spire-bundle-cfg.yaml`,  this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-bundle
  namespace: spire
```

Should probably be this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-bundle
  namespace: {{ .Release.Namespace }}
```

Otherwise, this will happen when you try to install to a different namespace:

```
time="2023-06-07T20:06:58Z" level=error msg="Server crashed" error="one or more notifiers returned an error: rpc error: code = Internal desc = notifier(k8sbundle): unable to update: unable to get list: configmaps \"spire-bundle\" is forbidden: User \"system:serviceaccount:spire2:spire-server\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"spire\""
```
