### ISSUE TITLE
Error while installing aws-load-balancer-controller CRDs from github url

### ISSUE THREAD

**Issue by cxreboll** [aws/eks-charts#964]
**Describe the bug**

There is a typo on aws-load-balancer-controller readme instructions. There is an extra slash '/' in the CDR URL which throws an error when executing it with `kubectl apply`

Instead of this:

`kubectl apply -k "github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller//crds?ref=master"`

Should be this:

`kubectl apply -k "github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller/crds?ref=master"`

**Steps to reproduce**

`kubectl apply -k "github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller//crds?ref=master"`

**Expected outcome**
We should see something like the following:

```
kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master"
customresourcedefinition.apiextensions.k8s.io/ingressclassparams.elbv2.k8s.aws created
customresourcedefinition.apiextensions.k8s.io/targetgroupbindings.elbv2.k8s.aws created
```

**Environment**

* Chart name: [aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller)
* Chart version: v2.5.2
* Kubernetes version: 1.24
* Using EKS (yes/no), if so version? 1.24

**Additional Context**:

```
bash --version
GNU bash, version 5.1.4(1)-release (x86_64-apple-darwin20.2.0)
```

**Comment by rabbagliettiandrea** [comment]
Same here, working helmfile.yaml:

```
repositories:
 - name: eks
   url: https://aws.github.io/eks-charts

releases:
- name: aws-load-balancer-controller
  namespace: kube-system
  chart: eks/aws-load-balancer-controller
  version: 1.5.4
  values:
  - values.yaml
  hooks:
  - events: ["prepare"]
    showlogs: true
    command: "kubectl"
    args:
    - "apply"
    - "-k"
    - "github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master"
  - events: ["postuninstall"]
    showlogs: true
    command: "kubectl"
    args:
    - "delete"
    - "-k"
    - "github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master"
```
